name: Main Taski Workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:

      # копируем код проекта в рабочую директорию раннера
    - name: check out code
      uses: actions/checkout@v3

      # устанавливаем python
    - name: set up python
      uses: actions/setup-python@v4
      with: 
        python-version: 3.12

      # Обновляем pip, устанавливаем flake8 и flake8-isort, 
      # устанавливаем зависимости проекта
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install flake8==6.0.0 flake8-isort==6.0.0
        pip install -r ./backend/requirements.txt

      # запускаем flake8 и тесты
    - name: test with flake8 and django_test
      run: | 
        python -m flake8 backend/
        cd backend/
        python manage.py test
       

  

